config/routes.rb
Rails.application.routes.draw do
  root to: 'books#index'
  
  get 'all' => 'books#all', as: 'all_books'
  get 'search' => 'books#search'
  
  resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  # validations
  validates :name, presence: true
  
  validates :author, presence: true
  
  validates :description, length: { minimum: 100 }
  
  validates :almaty_quantity, presence: true, numericality: {
    only_integer: true, greater_than_or_equal_to: 0
  }
    
  validates :shymkent_quantity, presence: true, numericality: {
    only_integer: true, greater_than_or_equal_to: 0
  }
  
  validates :image_src, format: {
    with: /\w+\.(jpg|png|jpeg)\z/i,
    message: 'must be a JPG, JPEG, or PNG image'
  }

  # get newest 20 books
  def self.newest
    order('created_at DESC').limit(20)
  end

  def self.all_ordered_by_name
    order('name ASC')
  end

  def self.search(query)
    q = '%' + query + '%'
    where('name LIKE ?', q)
  end

  def almaty_out_of_stock?
    almaty_quantity.blank? || almaty_quantity.zero?
  end

  def shymkent_out_of_stock?
    shymkent_quantity.blank? || shymkent_quantity.zero?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.newest
  end

  def all
    @books = Book.all_ordered_by_name
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to @book, notice: 'Книга была успешна добавлена!'
    else
      render :new
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to @book, notice: 'Книга была успешна обновлена!'
    else
      render :edit
    end
  end

  def search
    @query = params[:query]
    @books = Book.search(params[:query])
  end

  private

  def book_params
    params.require(:book)
      .permit(:name, :author, :description, :almaty_quantity, :shymkent_quantity, :image_src, :category, :visible)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper

  def availability(book)
    if book.almaty_out_of_stock? && book.shymkent_out_of_stock?
      return content_tag :span, 'не в наличии', class: 'out-of-stock'
    end

    if !book.almaty_out_of_stock? && !book.shymkent_out_of_stock?
      return content_tag :span, 'в наличии (Алматы и Шымкент)', class: 'in-stock'
    end

    if book.almaty_out_of_stock? && !book.shymkent_out_of_stock?
      return content_tag :span, 'в наличии (Шымкент)', class: 'in-stock'
    end

    if !book.almaty_out_of_stock? && book.shymkent_out_of_stock?
      return content_tag :span, 'в наличии (Алматы)', class: 'in-stock'
    end
  end

  def cover(book)
    image_tag book.image_src, 
      alt: "Обложка книги #{book.name}",
      class: 'absolute inset-0 w-full h-full object-cover rounded-lg'
  end
  
end

app/views/books/_cards.html.erb
<% books.each do |book| %>
  <section class="flex p-6 my-4 bg-green-50">
      <div class="flex-none w-48 h-72 relative">
        <%= link_to cover(book), book %>
      </div>

      <div class="flex-auto p-6">
        <h1 class="flex-auto text-xl font-bold pb-2">
          <%= link_to book.name, book, class: 'text-blue-500 text-2xl hover:underline hover:text-blue-500' %>
        </h1>
        <div class="w-full flex-none text-sm font-medium text-gray-500 mt-2">
          <%= availability book %>
        </div>
        <p class="text-base text-gray-600 my-4 font-bold">
          📗🖊️ <%= book.author %>
        </p>
        <p>
          <%= truncate book.description, length: 235, separator: ' ' %>
        </p>
      </div>
  </section>
<% end %>

app/views/books/_form.html.erb
<%= form_with(model: book, local: true, class: 'flex flex-col') do |f| %>

  <% unless book.name.blank? %>
    <h1 class='text-xl font-bold mb-5'>
      <%= book.name %>
    </h1>
  <% end %>

  <div class="mb-4">
    <%= book.errors.full_messages.to_sentence %>
  </div>

  <div class="mb-4">
    <%= f.label :name, 'Название', class: 'text-gray-600' %><br>
    <%= f.text_field :name,
                      autofocus: true, 
                      size: 33,
                      class: 'focus:border-blue-500 focus:ring-1 focus:ring-blue-500 focus:outline-none text-base text-black placeholder-gray-500 border-2 border-blue-200 py-2 pl-4 w-96' %>
  </div>

  <div class="mb-4">
    <%= f.label :author, 'Автор', class: 'text-gray-600' %><br>
    <%= f.text_field :author, 
                      size: 33,
                      class: 'focus:border-blue-500 focus:ring-1 focus:ring-blue-500 focus:outline-none text-base text-black placeholder-gray-500 border-2 border-blue-200 py-2 pl-4 w-96' %>
  </div>

  <div class="mb-4">
    <%= f.label :description, 'Описание', class: 'text-gray-600' %><br>
    <%= f.text_area :description, 
                    rows: 9, 
                    cols: 65,
                    class: 'focus:border-blue-500 focus:ring-1 focus:ring-blue-500 focus:outline-none text-base text-black placeholder-gray-500 border-2 border-blue-200 py-2 pl-4 w-full' %>
  </div>

  <div class="mb-4">
    <%= f.label :image_src, 'Ссылка на обложку', class: 'text-gray-600' %><br>
    <%= f.text_field :image_src, 
                      size: 33,
                      class: 'focus:border-blue-500 focus:ring-1 focus:ring-blue-500 focus:outline-none text-base text-black placeholder-gray-500 border-2 border-blue-200 py-2 pl-4 w-96' %>
  </div>

  <div class="mb-4">
    <%= f.label :category, 'Категория', class: 'text-gray-600' %><br>
    <%= f.text_field :category, 
                      size: 33,
                      list: 'book_categories',
                      class: 'focus:border-blue-500 focus:ring-1 focus:ring-blue-500 focus:outline-none text-base text-black placeholder-gray-500 border-2 border-blue-200 py-2 pl-4 w-96' %>
  </div>
  
  <div class="mb-4">
    <%= f.label :almaty_quantity, 'Количество (Алматы)', class: 'text-gray-600' %><br>
    <%= f.number_field :almaty_quantity, 
                        min: 0, 
                        size: 33,
                        class: 'focus:border-blue-500 focus:ring-1 focus:ring-blue-500 focus:outline-none text-base text-black placeholder-gray-500 border-2 border-blue-200 py-2 pl-4 w-96' %>
  </div>
  
  <div class="mb-4">
    <%= f.label :shymkent_quantity, 'Количество (Шымкент)', class: 'text-gray-600' %><br>
    <%= f.number_field :shymkent_quantity, 
                        min: 0, 
                        size: 33,
                        class: 'focus:border-blue-500 focus:ring-1 focus:ring-blue-500 focus:outline-none text-base text-black placeholder-gray-500 border-2 border-blue-200 py-2 pl-4 w-96' %>
  </div>

  <div class="mb-4">
    <%= f.submit 'Сохранить',
                  class: 'cursor-pointer text-lg font-bold bg-blue-500 text-white px-6 py-2 inline-block mr-6' %>
  </div>

<% end %>

<datalist id="book_categories">
  <option value="Художественная литература">
  <option value="Бизнес">
  <option value="Техническая литература">
  <option value="Бухшалтерская литература">
  <option value="Популярная психология">
  <option value="Юридическая литература">
  <option value="Саморазвитие">
  <option value="Менеджмент">
  <option value="Другое">
</datalist>

app/views/books/all.html.erb
<div class="text-2xl font-bold pb-2">Все книги</div>

<%= render 'cards', books: @books %>

app/views/books/edit.html.erb
<div class="text-2xl font-bold pb-2">
  Редактировать книгу
  "<%= @book.name %>"
</div>

<section class="flex p-6 my-4 bg-green-50">
  <%= render 'form', book: @book %>
</section>

app/views/books/index.html.erb
<div class="text-2xl font-bold pb-2">Новинки</div>

<%= link_to 'Добавить книгу',
            new_book_path,
            class: 'text-lg font-bold bg-blue-500 text-white px-6 py-2 inline-block mr-6' %>

<%= render 'cards', books: @books %>

app/views/books/new.html.erb
<div class="text-2xl font-bold pb-2">
  Добавить новую книгу
</div>

<section class="flex p-6 my-4 bg-green-50">
  <%= render 'form', book: @book, categories: @categories %>
</section>

app/views/books/search.html.erb
<div class="text-2xl font-bold pb-2">
  Результаты поиска по запросу 
  "<%= @query %>"
</div>

<%= render 'cards', books: @books %>

app/views/books/show.html.erb
<div class="text-2xl font-bold pb-2">Детальная информация о книге</div>

<section class="flex p-6 my-4 bg-green-50">
  <div class="flex-none w-48 h-72 relative">
    <%= cover(@book) %>
  </div>

  <div class="flex-auto p-6">
    <h1 class="flex-auto text-2xl font-bold">
      <%= @book.name %>
    </h1>
    <p class="text-base text-gray-600 my-4 font-bold">
      📗🖊️ <%= @book.author %>
    </p>
    <p class="my-2">
      <%= @book.description %>
    </p>
  </div>
</section>

<section class="p-6 my-4 bg-green-50">
  <%= link_to 'Редактировать',
              edit_book_path(@book), 
              class: 'text-lg font-bold bg-blue-500 text-white px-6 py-2 inline-block mr-4' %>

  <%#= link_to 'Скрыть',
              @book,
              method: :delete,
              data: { confirm: "Вы уверены, что хотите скрыть книгу «#{@book.name}»?" },
              class: 'text-lg font-bold bg-red-500 text-white px-6 py-2 inline-block mr-4' %>
</section>

app/views/layouts/_flash.html.erb
<% if flash[:notice] %>
  <p class="text-sm text-white text-center py-2 bg-green-500 mb-4 font-bold">
    <%= flash[:notice] %>
  </p>
<% end %>

<% if flash[:alert] %>
  <p class="text-sm text-white text-center py-2 bg-red-500 mb-4 font-bold">
    <%= flash[:alert] %>
  </p>
<% end %>

app/views/layouts/_header.html.erb
<header class="border-solid border-b-2 border-yellow-600 mb-5 pb-5">
  <nav class="flex flex-row justify-between items-center">
    <div>
      <%= link_to image_tag('evrika_animated_logo.gif', class: 'w-full'), root_path %>
        <span class="text-lg font-bold uppercase text-yellow-600 text-center block tracking-widest mt-1">Библиотека</span>
    </div>

    <ul class="flex flex-row">
      <li class="border-r-2 border-white">
        <%= link_to 'Новинки', root_path, class: 'block w-28 px-4 py-2 bg-blue-500 hover:bg-blue-500 text-white text-center text-lg capitalize' %>
      </li>
      <li class="border-r-2 border-white">
        <%= link_to 'Все 📗', all_books_path, class: 'block w-28 px-4 py-2 bg-blue-500 hover:bg-blue-500 text-white text-center text-lg capitalize' %>
      </li>
      <li class="border-r-2 border-white">
        <a href="order.html" class="block w-28 px-4 py-2 bg-blue-500 hover:bg-blue-500 text-white text-center text-lg capitalize">Заказы</a>
      </li>
      <li class="border-r-2 border-white">
        <a href="return.html" class="block w-28 px-4 py-2 bg-blue-500 hover:bg-blue-500 text-white text-center text-lg capitalize">Вернуть</a>
      </li>
    </ul>
  </nav>

  <div class="mt-5">
    <form action="/search" method="get" class="flex flex-row">
      <input
        type="text"
        name="query"
        id="search"
        placeholder="Название книги..."
        class="focus:border-blue-500 focus:ring-1 focus:ring-blue-500 focus:outline-none w-full text-base text-black placeholder-gray-500 border-2 border-blue-200 py-2 pl-4">
      <input type="submit" value="Искать 👀" class="text-white bg-yellow-600 hover:bg-blue-600 ml-2 px-2 cursor-pointer text-lg">
    </form>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bibliotheca</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= stylesheet_link_tag "https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" %>
  </head>

  <body>
    <div class="max-w-3xl mx-auto px-6 py-10">

      <%= render 'layouts/header' %>

      <main class="pt-3 pb-3">
        <%= render 'layouts/flash' %>
        
        <%= yield %>
      </main>

    </div>
  </body>
</html>